# TV Script Generation
In this project, you'll generate your own [Simpsons](https://en.wikipedia.org/wiki/The_Simpsons) TV scripts using RNNs.  You'll be using part of the [Simpsons dataset](https://www.kaggle.com/wcukierski/the-simpsons-by-the-data) of scripts from 27 seasons.  The Neural Network you'll build will generate a new TV script for a scene at [Moe's Tavern](https://simpsonswiki.com/wiki/Moe's_Tavern).
## Get the Data
The data is already provided for you.  You'll be using a subset of the original dataset.  It consists of only the scenes in Moe's Tavern.  This doesn't include other versions of the tavern, like "Moe's Cavern", "Flaming Moe's", "Uncle Moe's Family Feed-Bag", etc..

In [2]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
import helper

data_dir = './data/simpsons/moes_tavern_lines.txt'
text = helper.load_data(data_dir)
# Ignore notice, since we don't use it for analysing the data
print(text)
print(set(text))
# print((list(set(text))))
#print(text)

a = text.split()
print(len(set(a)))
# print(set(a))
print(type(text))


[YEAR DATE 1989] © Twentieth Century Fox Film Corporation. All rights reserved.

Moe_Szyslak: (INTO PHONE) Moe's Tavern. Where the elite meet to drink.
Bart_Simpson: Eh, yeah, hello, is Mike there? Last name, Rotch.
Moe_Szyslak: (INTO PHONE) Hold on, I'll check. (TO BARFLIES) Mike Rotch. Mike Rotch. Hey, has anybody seen Mike Rotch, lately?
Moe_Szyslak: (INTO PHONE) Listen you little puke. One of these days I'm gonna catch you, and I'm gonna carve my name on your back with an ice pick.
Moe_Szyslak: What's the matter Homer? You're not your normal effervescent self.
Homer_Simpson: I got my problems, Moe. Give me another one.
Moe_Szyslak: Homer, hey, you should not drink to forget your problems.
Barney_Gumble: Yeah, you should only drink to enhance your social skills.


Moe_Szyslak: Ah, isn't that nice. Now, there is a politician who cares.
Barney_Gumble: If I ever vote, it'll be for him. (BELCH)


Barney_Gumble: Hey Homer, how's your neighbor's store doing?
Homer_Simpson: Lousy. He just 

## Explore the Data
Play around with `view_sentence_range` to view different parts of the data.

In [3]:
view_sentence_range = (0, 100)

"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
import numpy as np

print('Dataset Stats')
print('Roughly the number of unique words: {}'.format(len({word: None for word in text.split()})))
#######handy way other than set to count unique words in dataset


##print({word: None for word in text.split()})


scenes = text.split('\n\n')
print('Number of scenes: {}'.format(len(scenes)))
#print(scenes)

# arbit = text.split('Moe_Szyslak:')
# print('No. of arbit text: {}'.format(len(arbit)))
# print(arbit)

##scene.count count the occurences of newline in the scene
sentence_count_scene = [scene.count('\n') for scene in scenes]
##print(len(sentence_count_scene))
print('Average number of sentences in each scene: {}'.format(np.average(sentence_count_scene)))

sentences = [sentence for scene in scenes for sentence in scene.split('\n')]
print('Number of lines: {}'.format(len(sentences)))
word_count_sentence = [len(sentence.split()) for sentence in sentences]
print('Average number of words in each line: {}'.format(np.average(word_count_sentence)))

print()
print('The sentences {} to {}:'.format(*view_sentence_range))
print('\n'.join(text.split('\n')[view_sentence_range[0]:view_sentence_range[1]]))
#print(text)

Dataset Stats
Roughly the number of unique words: 11501
Number of scenes: 263
Average number of sentences in each scene: 15.190114068441064
Number of lines: 4258
Average number of words in each line: 11.504462188821043

The sentences 0 to 100:
[YEAR DATE 1989] © Twentieth Century Fox Film Corporation. All rights reserved.

Moe_Szyslak: (INTO PHONE) Moe's Tavern. Where the elite meet to drink.
Bart_Simpson: Eh, yeah, hello, is Mike there? Last name, Rotch.
Moe_Szyslak: (INTO PHONE) Hold on, I'll check. (TO BARFLIES) Mike Rotch. Mike Rotch. Hey, has anybody seen Mike Rotch, lately?
Moe_Szyslak: (INTO PHONE) Listen you little puke. One of these days I'm gonna catch you, and I'm gonna carve my name on your back with an ice pick.
Moe_Szyslak: What's the matter Homer? You're not your normal effervescent self.
Homer_Simpson: I got my problems, Moe. Give me another one.
Moe_Szyslak: Homer, hey, you should not drink to forget your problems.
Barney_Gumble: Yeah, you should only drink to enhance 

## Implement Preprocessing Functions
The first thing to do to any dataset is preprocessing.  Implement the following preprocessing functions below:
- Lookup Table
- Tokenize Punctuation

### Lookup Table
To create a word embedding, you first need to transform the words to ids.  In this function, create two dictionaries:
- Dictionary to go from the words to an id, we'll call `vocab_to_int`
- Dictionary to go from the id to word, we'll call `int_to_vocab`

Return these dictionaries in the following tuple `(vocab_to_int, int_to_vocab)`

In [4]:
##here text has already in list type. i.e already splitted.

import numpy as np
import problem_unittests as tests
from collections import Counter
#print(len(text))
def create_lookup_tables(text):
    """
    Create lookup tables for vocabulary
    :param text: The text of tv scripts split into words
    :return: A tuple of dicts (vocab_to_int, int_to_vocab)
    """
    # TODO: Implement Function
#     print(type(text))
#     param_text = Counter(set(text))
    
    
#     vocab_to_int = {i:c for i,c in enumerate(param_text)}
#     int_to_vocab = {c:i for i,c in enumerate(param_text)}
    
#     return (vocab_to_int,int_to_vocab)




    counts = set(text)
    ##counter counts the frequency  of words appearing in the text. 
    
    #vocab = sorted(counts, key=counts.get, reverse=True)
    #sorting arranges in the decreasing order
    
    vocab_to_int = {word: ii for ii, word in enumerate(counts)}
    int_to_vocab = {ii:word for ii, word in enumerate(counts)}
    
    #int_to_vocab = {v:k for k, v in vocab_to_int.items()}
    return (vocab_to_int, int_to_vocab)



#print(len(text))
"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_create_lookup_tables(create_lookup_tables)


Tests Passed


### Tokenize Punctuation
We'll be splitting the script into a word array using spaces as delimiters.  However, punctuations like periods and exclamation marks make it hard for the neural network to distinguish between the word "bye" and "bye!".

Implement the function `token_lookup` to return a dict that will be used to tokenize symbols like "!" into "||Exclamation_Mark||".  Create a dictionary for the following symbols where the symbol is the key and value is the token:
- Period ( . )
- Comma ( , )
- Quotation Mark ( " )
- Semicolon ( ; )
- Exclamation mark ( ! )
- Question mark ( ? )
- Left Parentheses ( ( )
- Right Parentheses ( ) )
- Dash ( -- )
- Return ( \n )

This dictionary will be used to token the symbols and add the delimiter (space) around it.  This separates the symbols as it's own word, making it easier for the neural network to predict on the next word. Make sure you don't use a token that could be confused as a word. Instead of using the token "dash", try using something like "||dash||".

In [5]:
def token_lookup():
    """
    Generate a dict to turn punctuation into a token.
    :return: Tokenize dictionary where the key is the punctuation and the value is the token
    """
    # TODO: Implement Function
    
    keys = ['.', ',', '"', ';', '!', '?', '(',')', '--', '\n']
    values = ['||Period||', '||Comma||', '||Quotation_Mark||', '||Semicolon||', '||Exclamation_Mark||',
              '||Question_Mark||', '||Left_Parentheses||', '||Right_Parentheses||', '||Dash||',
              '||Return||'] 
    
    
    
    
    return dict(zip(keys,values))

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_tokenize(token_lookup)

Tests Passed


## Preprocess all the data and save it
Running the code cell below will preprocess all the data and save it to file.

In [6]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""

# Preprocess Training, Validation, and Testing Data
helper.preprocess_and_save_data(data_dir, token_lookup, create_lookup_tables)

# Check Point
This is your first checkpoint. If you ever decide to come back to this notebook or have to restart the notebook, you can start from here. The preprocessed data has been saved to disk.

In [7]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
import helper
import numpy as np
import problem_unittests as tests

int_text, vocab_to_int, int_to_vocab, token_dict = helper.load_preprocess()

## Build the Neural Network
You'll build the components necessary to build a RNN by implementing the following functions below:
- get_inputs
- get_init_cell
- get_embed
- build_rnn
- build_nn
- get_batches

### Check the Version of TensorFlow and Access to GPU

In [8]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
from distutils.version import LooseVersion
import warnings
import tensorflow as tf

# Check TensorFlow Version
assert LooseVersion(tf.__version__) >= LooseVersion('1.0'), 'Please use TensorFlow version 1.0 or newer'
print('TensorFlow Version: {}'.format(tf.__version__))

# Check for a GPU
if not tf.test.gpu_device_name():
    warnings.warn('No GPU found. Please use a GPU to train your neural network.')
else:
    print('Default GPU Device: {}'.format(tf.test.gpu_device_name()))

TensorFlow Version: 1.0.0
Default GPU Device: /gpu:0


### Input
Implement the `get_inputs()` function to create TF Placeholders for the Neural Network.  It should create the following placeholders:
- Input text placeholder named "input" using the [TF Placeholder](https://www.tensorflow.org/api_docs/python/tf/placeholder) `name` parameter.
- Targets placeholder
- Learning Rate placeholder

Return the placeholders in the following the tuple `(Input, Targets, LearingRate)`

In [9]:
def get_inputs():
    """
    Create TF Placeholders for input, targets, and learning rate.
    :return: Tuple (input, targets, learning rate)
    """
    # TODO: Implement Function
    
    Input = tf.placeholder(tf.int32,shape = [None,None], name = "input")
    
    print(Input)
    
    Targets = tf.placeholder(tf.int32,shape = [None,None], name = "targets")
    LearningRate = tf.placeholder(tf.float32, name = "lr")
    
    return (Input,Targets,LearningRate)


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_get_inputs(get_inputs)

Tensor("input:0", shape=(?, ?), dtype=int32)
Tests Passed


### Build RNN Cell and Initialize
Stack one or more [`BasicLSTMCells`](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/BasicLSTMCell) in a [`MultiRNNCell`](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/MultiRNNCell).
- The Rnn size should be set using `rnn_size`
- Initalize Cell State using the MultiRNNCell's [`zero_state()`](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/MultiRNNCell#zero_state) function
    - Apply the name "initial_state" to the initial state using [`tf.identity()`](https://www.tensorflow.org/api_docs/python/tf/identity)

Return the cell and initial state in the following tuple `(Cell, InitialState)`

In [10]:
def get_init_cell(batch_size, rnn_size):
    """
    Create an RNN Cell and initialize it.
    :param batch_size: Size of batches
    :param rnn_size: Size of RNNs
    :return: Tuple (cell, initialize state)
    """
    # TODO: Implement Function
    
#     lstm = tf.contrib.rnn.BasicLSTMCell(rnn_size)
#     cell = tf.contrib.rnn.MultiRNNCell([lstm])
#     initial_state = tf.identity(cell.zero_state(batch_size, tf.float32), name="initial_state")
#     return cell, initial_state
    print("batch_size===================")
    print(batch_size)
    
    print("rnn_size=====================")
    print(rnn_size)
    
    rnncell = tf.contrib.rnn.BasicLSTMCell(rnn_size)
    print("rnncell======================")
    print(rnncell)
    
    
    Cell = tf.contrib.rnn.MultiRNNCell([rnncell],1)
    
    print("Cell====================")
    print(Cell)
    
    initial_state = Cell.zero_state(batch_size, tf.float32)
    print("initial_state============================")
    print(initial_state)
    InitialState = tf.identity(initial_state, name="initial_state")
    print("InitialState=============================")
    print(InitialState)
    return (Cell,InitialState)

##what is initial state?


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_get_init_cell(get_init_cell)

batch_size===================
Tensor("Placeholder:0", dtype=int32)
rnn_size=====================
256
rnncell======================
Cell====================
initial_state============================
(LSTMStateTuple(c=<tf.Tensor 'zeros:0' shape=(?, 256) dtype=float32>, h=<tf.Tensor 'zeros_1:0' shape=(?, 256) dtype=float32>),)
InitialState=============================
Tensor("initial_state:0", shape=(1, 2, ?, 256), dtype=float32)
Tests Passed


### Word Embedding
Apply embedding to `input_data` using TensorFlow.  Return the embedded sequence.

In [11]:
def get_embed(input_data, vocab_size, embed_dim):
    """
    Create embedding for <input_data>.
    :param input_data: TF placeholder for text input.
    :param vocab_size: Number of words in vocabulary.
    :param embed_dim: Number of embedding dimensions
    :return: Embedded input.
    """
    # TODO: Implement Function
    print("vocab_size=======================")
    print(vocab_size)
    print("embed_dim==========================")
    print(embed_dim)
    
    print("inputdata====================")
    print(input_data)
    
    embedding = tf.Variable(tf.random_uniform((vocab_size,embed_dim),-1,1))
    print("embedding=================")
    print(embedding)
    
    embed = tf.nn.embedding_lookup(embedding,input_data)
    print("embed==========================")
    print(embed)
    
    return embed


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_get_embed(get_embed)

vocab_size=======================
27
embed_dim==========================
256
inputdata====================
Tensor("Placeholder:0", shape=(50, 5), dtype=int32)
embedding=================
Tensor("Variable/read:0", shape=(27, 256), dtype=float32)
embed==========================
Tensor("embedding_lookup:0", shape=(50, 5, 256), dtype=float32)
Tests Passed


### Build RNN
You created a RNN Cell in the `get_init_cell()` function.  Time to use the cell to create a RNN.
- Build the RNN using the [`tf.nn.dynamic_rnn()`](https://www.tensorflow.org/api_docs/python/tf/nn/dynamic_rnn)
 - Apply the name "final_state" to the final state using [`tf.identity()`](https://www.tensorflow.org/api_docs/python/tf/identity)

Return the outputs and final_state state in the following tuple `(Outputs, FinalState)` 

In [12]:
def build_rnn(cell, inputs):
    """
    Create a RNN using a RNN Cell
    :param cell: RNN Cell
    :param inputs: Input text data
    :return: Tuple (Outputs, Final State)
    """
    # TODO: Implement Function
    #tf.nn.dynamic_rnn(cell, inputs, sequence_length=None, initial_state=None, dtype=None, parallel_iterations=None, swap_memory=False, time_major=False, scope=None)

    ##but input has to be embed vectors not text
    print("cell==================")
    print(cell)
    
    print("inputs================")
    print(inputs)
    Outputs, final_state = tf.nn.dynamic_rnn(cell, inputs = inputs, dtype=tf.float32)
    print("outputs===================")
    print(Outputs)
    final_state = tf.identity(final_state, name = "final_state")
    return (Outputs, final_state)
    
#     return Outputs, FinalState


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_build_rnn(build_rnn)

cell==================
inputs================
Tensor("Placeholder:0", shape=(?, ?, 256), dtype=float32)
outputs===================
Tensor("rnn/transpose:0", shape=(?, ?, 256), dtype=float32)
Tests Passed


### Build the Neural Network
Apply the functions you implemented above to:
- Apply embedding to `input_data` using your `get_embed(input_data, vocab_size, embed_dim)` function.
- Build RNN using `cell` and your `build_rnn(cell, inputs)` function.
- Apply a fully connected layer with a linear activation and `vocab_size` as the number of outputs.

Return the logits and final state in the following tuple (Logits, FinalState) 

In [13]:
def build_nn(cell, rnn_size, input_data, vocab_size):

    """
Build part of the neural network
    :param cell: RNN cell
    :param rnn_size: Size of rnns
    :param input_data: Input data
    :param vocab_size: Vocabulary size
    :return: Tuple (Logits, FinalState)
    """
#     # TODO: Implement Function
#     print("rnn_size==========================")
#     print(rnn_size)
#     print("input_data==========================")
#     print(input_data)
#     print("vocab_size===========================")
#     print(vocab_size)
    
#     inputs = get_embed(input_data, vocab_size, 200)
#     print("inputs=========================================")
#     print(inputs)
#     outputs, final_state = build_rnn(cell,inputs)
#     print("outputs====================================")
#     print(outputs)
    
#     # Unfold output from 3d to 2d
#     #output = tf.reshape(outputs, [-1, rnn_size])
    
#     # Now connect the RNN outputs to a softmax layer
#     softmax_w = tf.Variable(tf.truncated_normal((rnn_size, vocab_size), stddev=0.1))
#     print("softmax=================================")
#     print(softmax_w)
#     softmax_b = tf.Variable(tf.zeros(vocab_size))
#     print("softmax_b============================")
#     print(softmax_b)
    
#     #logits = tf.matmul(output, softmax_w) + softmax_b
    
#     # Refold back to 3d
# #     logits = tf.reshape(logits, input_data.shape.as_list() + [vocab_size])
#     logits = tf.contrib.layers.fully_connected(outputs, vocab_size, activation_fn=None)
#     print("logits==================================")
#     print(logits)
    
#     return logits, final_state
    
    inputs = get_embed(input_data, vocab_size, 300)
    outputs, final_state = build_rnn(cell, inputs)
    logits = tf.contrib.layers.fully_connected(outputs, vocab_size, activation_fn=None)
    return (logits, final_state)
    
"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_build_nn(build_nn)

vocab_size=======================
27
embed_dim==========================
300
inputdata====================
Tensor("Placeholder:0", shape=(128, 5), dtype=int32)
embedding=================
Tensor("Variable/read:0", shape=(27, 300), dtype=float32)
embed==========================
Tensor("embedding_lookup:0", shape=(128, 5, 300), dtype=float32)
cell==================
inputs================
Tensor("embedding_lookup:0", shape=(128, 5, 300), dtype=float32)
outputs===================
Tensor("rnn/transpose:0", shape=(128, 5, 256), dtype=float32)
Tests Passed


### Batches
Implement `get_batches` to create batches of input and targets using `int_text`.  The batches should be a Numpy array with the shape `(number of batches, 2, batch size, sequence length)`. Each batch contains two elements:
- The first element is a single batch of **input** with the shape `[batch size, sequence length]`
- The second element is a single batch of **targets** with the shape `[batch size, sequence length]`

If you can't fill the last batch with enough data, drop the last batch.

For exmple, `get_batches([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], 2, 3)` would return a Numpy array of the following:
```
[
  # First Batch
  [
    # Batch of Input
    [[ 1  2  3], [ 7  8  9]],
    # Batch of targets
    [[ 2  3  4], [ 8  9 10]]
  ],
 
  # Second Batch
  [
    # Batch of Input
    [[ 4  5  6], [10 11 12]],
    # Batch of targets
    [[ 5  6  7], [11 12 13]]
  ]
]
```

In [14]:
def get_batches(int_text, batch_size, seq_length):
    """
    Return batches of input and target
    :param int_text: Text with the words replaced by their ids
    :param batch_size: The size of batch
    :param seq_length: The length of sequence
    :return: Batches as a Numpy array
    """
    # TODO: Implement Function
    
    print("len(int_text)====================")
    print(len(int_text))
    
    print("batch_size, seq_length===================")
    print(batch_size,seq_length)
    n_batches = len(int_text)//(batch_size*seq_length)
    print("no. of batches==========================")
    print(n_batches)
    
    
    # printing only full batches
    int_text = int_text[:n_batches*batch_size*seq_length+1]
    print("int_text full batches===================")
    print(len(int_text))
    
    #it should be 4480 its coming 4481, the mystery continues
    
    
    
# Initialize result & calculate skip distance
    result=np.ndarray(shape=(n_batches,2,batch_size,seq_length), dtype=int)
    print("result.shape=====================================")
    print(result.shape)
#skipping words
    skpd = n_batches*seq_length  
    print("skpd===========================================")
    print(skpd)

# First loop steps at batch_size * seq_length
    for b in range(n_batches):
        batch_idx = b*seq_length
        print("batch_index=====================")
        print(batch_idx)
        
        
        x , y= [], []
        for bb in range(batch_size):
            idx = batch_idx + (bb*skpd) # get starting index for batch
            print(idx)
            x_idx = idx
            y_idx = idx+1 
            print(y_idx)
            result[b][0][bb] = int_text[x_idx:x_idx+seq_length]
            print(result[b][0][bb])
            result[b][1][bb] = int_text[y_idx:y_idx+seq_length]                   
    return result
    
    
   

  #    int_text = int_text[16:]
#     n_batches = (len(int_text)-1)//(batch_size * seq_length)    
#     int_text = int_text[:n_batches * batch_size * seq_length + 1]
#     int_text_sequences = [int_text[i*seq_length:i*seq_length+seq_length] for i in range(0, n_batches * batch_size)]
#     int_text = int_text[1:]
#     int_text_targets = [int_text[i*seq_length:i*seq_length+seq_length] for i in range(0, n_batches * batch_size)]
#     output = []
#     for batch in range(n_batches):
#         inputs = []
#         targets = []
#         for size in range(batch_size):
#             inputs.append(int_text_sequences[size * n_batches + batch])
#             targets.append(int_text_targets[size * n_batches + batch])
#         output.append([inputs, targets])
#     return np.array(output)


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_get_batches(get_batches)

len(int_text)====================
5000
batch_size, seq_length===================
128 5
no. of batches==========================
7
int_text full batches===================
4481
result.shape=====================================
(7, 2, 128, 5)
skpd===========================================
35
batch_index=====================
0
0
1
[0 1 2 3 4]
35
36
[35 36 37 38 39]
70
71
[70 71 72 73 74]
105
106
[105 106 107 108 109]
140
141
[140 141 142 143 144]
175
176
[175 176 177 178 179]
210
211
[210 211 212 213 214]
245
246
[245 246 247 248 249]
280
281
[280 281 282 283 284]
315
316
[315 316 317 318 319]
350
351
[350 351 352 353 354]
385
386
[385 386 387 388 389]
420
421
[420 421 422 423 424]
455
456
[455 456 457 458 459]
490
491
[490 491 492 493 494]
525
526
[525 526 527 528 529]
560
561
[560 561 562 563 564]
595
596
[595 596 597 598 599]
630
631
[630 631 632 633 634]
665
666
[665 666 667 668 669]
700
701
[700 701 702 703 704]
735
736
[735 736 737 738 739]
770
771
[770 771 772 773 774]
805
806
[80

## Neural Network Training
### Hyperparameters
Tune the following parameters:

- Set `num_epochs` to the number of epochs.
- Set `batch_size` to the batch size.
- Set `rnn_size` to the size of the RNNs.
- Set `seq_length` to the length of sequence.
- Set `learning_rate` to the learning rate.
- Set `show_every_n_batches` to the number of batches the neural network should print progress.

In [23]:
# Number of Epochs
num_epochs = 100
# Batch Size
batch_size = 128
# RNN Size
rnn_size = 128
# Sequence Length
seq_length = 50
# Learning Rate
learning_rate = 0.1
# Show stats for every n number of batches
show_every_n_batches = 5

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
save_dir = './save'

### Build the Graph
Build the graph using the neural network you implemented.

In [24]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
from tensorflow.contrib import seq2seq

train_graph = tf.Graph()
with train_graph.as_default():
    vocab_size = len(int_to_vocab)
    input_text, targets, lr = get_inputs()
    input_data_shape = tf.shape(input_text)
    cell, initial_state = get_init_cell(input_data_shape[0], rnn_size)
    logits, final_state = build_nn(cell, rnn_size, input_text, vocab_size)

    # Probabilities for generating words
    probs = tf.nn.softmax(logits, name='probs')

    # Loss function
    cost = seq2seq.sequence_loss(
        logits,
        targets,
        tf.ones([input_data_shape[0], input_data_shape[1]]))

    # Optimizer
    optimizer = tf.train.AdamOptimizer(lr)

    # Gradient Clipping
    gradients = optimizer.compute_gradients(cost)
    capped_gradients = [(tf.clip_by_value(grad, -1., 1.), var) for grad, var in gradients]
    train_op = optimizer.apply_gradients(capped_gradients)

Tensor("input:0", shape=(?, ?), dtype=int32)
batch_size===================
Tensor("strided_slice:0", shape=(), dtype=int32)
rnn_size=====================
128
rnncell======================
Cell====================
initial_state============================
(LSTMStateTuple(c=<tf.Tensor 'zeros:0' shape=(?, 128) dtype=float32>, h=<tf.Tensor 'zeros_1:0' shape=(?, 128) dtype=float32>),)
InitialState=============================
Tensor("initial_state:0", shape=(1, 2, ?, 128), dtype=float32)
vocab_size=======================
6779
embed_dim==========================
300
inputdata====================
Tensor("input:0", shape=(?, ?), dtype=int32)
embedding=================
Tensor("Variable/read:0", shape=(6779, 300), dtype=float32)
embed==========================
Tensor("embedding_lookup:0", shape=(?, ?, 300), dtype=float32)
cell==================
inputs================
Tensor("embedding_lookup:0", shape=(?, ?, 300), dtype=float32)
outputs===================
Tensor("rnn/transpose:0", shape=(?, ?, 1

## Train
Train the neural network on the preprocessed data.  If you have a hard time getting a good loss, check the [forms](https://discussions.udacity.com/) to see if anyone is having the same problem.

In [25]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
batches = get_batches(int_text, batch_size, seq_length)

with tf.Session(graph=train_graph) as sess:
    sess.run(tf.global_variables_initializer())

    for epoch_i in range(num_epochs):
        state = sess.run(initial_state, {input_text: batches[0][0]})

        for batch_i, (x, y) in enumerate(batches):
            feed = {
                input_text: x,
                targets: y,
                initial_state: state,
                lr: learning_rate}
            train_loss, state, _ = sess.run([cost, final_state, train_op], feed)

            # Show every <show_every_n_batches> batches
            if (epoch_i * len(batches) + batch_i) % show_every_n_batches == 0:
                print('Epoch {:>3} Batch {:>4}/{}   train_loss = {:.3f}'.format(
                    epoch_i,
                    batch_i,
                    len(batches),
                    train_loss))

    # Save Model
    saver = tf.train.Saver()
    saver.save(sess, save_dir)
    print('Model Trained and Saved')

len(int_text)====================
69100
batch_size, seq_length===================
128 50
no. of batches==========================
10
int_text full batches===================
64001
result.shape=====================================
(10, 2, 128, 50)
skpd===========================================
500
batch_index=====================
0
0
1
[2008 4149 4428 3303  126  833 5528 2179 2641 3905 3302 2231  445 4447 2179
 4319 3780 2492 5999 4674 5999 5017 5999 3835 6235 1204 4627 2506 1528 5999
 6733 2179 4319 2008 4149 4428 3303  126 4339 4301 5999 4839 1755 2179 4149
  445 3960  126 6235 6733]
500
501
[2179 2683 3878 3155 2246 2389 2286 2179 3905  665 5999 3905 3517 5999 2612
  487 5999 1124 2179 4319 3118  616 4973 6695 4627 4319 6465 1292 2653 3171
 4259 5999 2081 2683 4627 4319 6465 5702 3491 4319 6465  714 4627 2653 1901
 4627  297 5999 3948 3054]
1000
1001
[4146 3468 2721 6305 2179 4709 5826 5999 6556 4973 1001 2679 3905 3025 1500
 4539 3339 4943 2594 1593  344 2792 2141 3905 1087 4845 21

## Save Parameters
Save `seq_length` and `save_dir` for generating a new TV script.

In [26]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
# Save parameters for checkpoint
helper.save_params((seq_length, save_dir))

# Checkpoint

In [27]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
import tensorflow as tf
import numpy as np
import helper
import problem_unittests as tests

_, vocab_to_int, int_to_vocab, token_dict = helper.load_preprocess()
seq_length, load_dir = helper.load_params()

## Implement Generate Functions
### Get Tensors
Get tensors from `loaded_graph` using the function [`get_tensor_by_name()`](https://www.tensorflow.org/api_docs/python/tf/Graph#get_tensor_by_name).  Get the tensors using the following names:
- "input:0"
- "initial_state:0"
- "final_state:0"
- "probs:0"

Return the tensors in the following tuple `(InputTensor, InitialStateTensor, FinalStateTensor, ProbsTensor)` 

In [28]:
def get_tensors(loaded_graph):
    """
    Get input, initial state, final state, and probabilities tensor from <loaded_graph>
    :param loaded_graph: TensorFlow graph loaded from file
    :return: Tuple (InputTensor, InitialStateTensor, FinalStateTensor, ProbsTensor)
    """
    # TODO: Implement Function
    InputTensor = loaded_graph.get_tensor_by_name("input:0")
    InitialStateTensor = loaded_graph.get_tensor_by_name("initial_state:0") 
    FinalStateTensor = loaded_graph.get_tensor_by_name("final_state:0") 
    ProbsTensor = loaded_graph.get_tensor_by_name("probs:0")
    return  (InputTensor, InitialStateTensor, FinalStateTensor, ProbsTensor)


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_get_tensors(get_tensors)

Tests Passed


### Choose Word
Implement the `pick_word()` function to select the next word using `probabilities`.

In [29]:
import random


def pick_word(probabilities, int_to_vocab):
    """
    Pick the next word in the generated text
    :param probabilities: Probabilites of the next word
    :param int_to_vocab: Dictionary of word ids as the keys and words as the values
    :return: String of the predicted word
    """
    # TODO: Implement Function
#     print(probabilities)
#     print(int_to_vocab)
    

#     print(np.random.choice(list(int_to_vocab.values()), 1, p=probabilities)[0])
    #return np.random.choice(int_to_vocab, probabilities)
    return np.random.choice(list(int_to_vocab.values()), 1, p=probabilities)[0]
    """
    DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
    """
tests.test_pick_word(pick_word)

Tests Passed


## Generate TV Script
This will generate the TV script for you.  Set `gen_length` to the length of TV script you want to generate.

In [30]:
gen_length = 200
# homer_simpson, moe_szyslak, or Barney_Gumble
prime_word = 'homer_simpson'

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
loaded_graph = tf.Graph()
with tf.Session(graph=loaded_graph) as sess:
    # Load saved model
    loader = tf.train.import_meta_graph(load_dir + '.meta')
    loader.restore(sess, load_dir)

    # Get Tensors from loaded model
    input_text, initial_state, final_state, probs = get_tensors(loaded_graph)

    # Sentences generation setup
    gen_sentences = [prime_word + ':']
    prev_state = sess.run(initial_state, {input_text: np.array([[1]])})

    # Generate sentences
    for n in range(gen_length):
        # Dynamic Input
        dyn_input = [[vocab_to_int[word] for word in gen_sentences[-seq_length:]]]
        dyn_seq_length = len(dyn_input[0])

        # Get Prediction
        probabilities, prev_state = sess.run(
            [probs, final_state],
            {input_text: dyn_input, initial_state: prev_state})
        
        pred_word = pick_word(probabilities[dyn_seq_length-1], int_to_vocab)

        gen_sentences.append(pred_word)
    
    # Remove tokens
    tv_script = ' '.join(gen_sentences)
    for key, token in token_dict.items():
        ending = ' ' if key in ['\n', '(', '"'] else ''
        tv_script = tv_script.replace(' ' + token.lower(), key)
    tv_script = tv_script.replace('\n ', '\n')
    tv_script = tv_script.replace('( ', '(')
        
    print(tv_script)

homer_simpson: i live with joey heatherton) special for you again? entire steel industry's gay teddy thank you all moe, all a lot call me all right, every time!
homer_simpson: oh..
homer_simpson: those freed iranian hostages.. the. yeah, it was you not hurt the process. he(giving the new moe-lennium.(smiling) your information? dearest?
homer_simpson:(grumbling) he doesn't in your best musical in which when it sucks to dinner was last me, don't wanna marry have i'm thankful to michael, peter window, skinner don't got these game.(stagy) are they! i talk your heart. i'm doing?
homer_simpson:(woozy) we were duff.
billy_the_kid: go, government.
moe_szyslak: i lost and down to buzziness..
homer_simpson: so freaking far away" booze.
marge_simpson:(talk-sings) 'cause
if i got seen look, i had..(, then realizing moan) this is for from the boxcars, but you said you could hear mindless droning, somewhere


# The TV Script is Nonsensical
It's ok if the TV script doesn't make any sense.  We trained on less than a megabyte of text.  In order to get good results, you'll have to use a smaller vocabulary or get more data.  Luckly there's more data!  As we mentioned in the begging of this project, this is a subset of [another dataset](https://www.kaggle.com/wcukierski/the-simpsons-by-the-data).  We didn't have you train on all the data, because that would take too long.  However, you are free to train your neural network on all the data.  After you complete the project, of course.
# Submitting This Project
When submitting this project, make sure to run all the cells before saving the notebook. Save the notebook file as "dlnd_tv_script_generation.ipynb" and save it as a HTML file under "File" -> "Download as". Include the "helper.py" and "problem_unittests.py" files in your submission.